// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		
		
		int numofTime = Integer.parseInt(args[0]);
		
		

		int morethanHalf=0;
		int lessthanHalf=0;

		for (int i=0;i<numofTime;i++)
		{
			double a = Math.random();

		if (a>0.5)
		 morethanHalf++;
		
		 else 
		lessthanHalf++;
		}

		

		System.out.println(">5.0: " + morethanHalf + " times");
		System.out.println("<= 5.0: " + lessthanHalf + " times");
		
		if (lessthanHalf != 0)
		{
		double ratio = (double) morethanHalf/lessthanHalf;
		System.out.println("Ratio: " + ratio);
		}

		
		
	


	   
	}
}
